site_name: SemT_py Documentation
site_description: Documentation for Semantic Enrichment of Tables Python Library
repo_url: https://github.com/aliduabubakari/semt_py
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting Started: 
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
  - Modules:
    - Auth Manager: modules/auth_manager.md
    - Dataset Manager: modules/dataset_manager.md
    - Extension Manager: modules/extension_manager.md
    - Modification Manager: modules/modification_manager.md
    - Reconciliation Manager: modules/reconciliation_manager.md
    - Table Manager: modules/table_manager.md
    - Utils: modules/utils.md
  - API Reference: api.md
  - Contributing: contributing.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: ["./semt_py"]  # Ensure this path is correct
          options:
            show_source: true